// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drnhhpaazbiujxdradtz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRybmhocGFhemJpdWp4ZHJhZHR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MTgzMTMsImV4cCI6MjA2NzI5NDMxM30.-58dhyOV3Xl14kv-KxaRbdoo6_iVtL8-Ji6_nKwWlJo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});